#!/bin/sh

update_drivers()
{
	[[ -n $(lspci | grep -iF nvidia) ]] && NVIDIA_FLAG=1
	if [[ $NVIDIA_FLAG = 1 && ! -e "/lib/modules/$KERNEL_RELEASE_/video/nvidia.ko" ]];
	then
		sudo emerge --usepkg -v nvidia-drivers
		sudo reboot
	fi
}

get_index() 
{
    echo -e "$1" |
    head --lines "$(( $2 + 1 ))" |
    tail --lines "1"
}

get_pci_device()
# $1 = single line of lspci input
# returns device id
{
	printf "$(echo "$1" | cut -d' ' -f1)\n"
}

gpu_info()
{
	VGA_=$(lspci | grep "VGA compatible controller")
	VGA_count_=$(echo "$VGA_" | wc -l) 

	if (( $VGA_count_ > 0 ))
	then
		for (( i = 0; i < $VGA_count_; i++ ))
		do
			printf "\n"
			PCI_=$(get_index "$VGA_" $i)
			printf "$(echo "$PCI_" | cut -d: -f3- | xargs)\n"
			PCI_=$(get_pci_device $PCI_)

			DRIVER_=$(cat /sys/bus/pci/devices/0000:$PCI_/driver_override | grep -v "(null)")
			[[ -z $DRIVER_ ]] && DRIVER_=$(lspci -k | grep "$PCI_" -A3 | grep "in use:" | cut -d: -f2 | xargs)
			[[ -z $DRIVER_ ]] && DRIVER_="(none)"
			printf "  Driver in use:\t$DRIVER_\n"
			if [[ -e /sys/bus/pci/devices/0000:$PCI_/current_link_speed ]]
			then
				LINK_SPEED_=$(cat /sys/bus/pci/devices/0000:$PCI_/current_link_speed)
				[[ -n $(echo $LINK_SPEED_ | grep -v Unknown) ]] && printf "  Current link speed:\t$LINK_SPEED_\n"
			fi
			(( 1 == $(cat /sys/bus/pci/devices/0000:$PCI_/boot_vga) )) && printf "  (Primary)\n"
		done
	fi
}

system_info()
{
	OS_=$(uname -o)
	ARCH_=$(uname -mp)
	KERNEL_RELEASE_=$(uname -r)
	[[ -e /usr/bin/sensors ]] && CPU_TEMP_=$(sensors | grep "Package id 0" | cut -d' ' -f5)
	MEMORY_=$(free -m --si | grep Mem | xargs | cut -d' ' -f2)
	SWAP_=$(free -m --si | grep Swap | xargs | cut -d' ' -f2)
	printf  "\n"
	printf  "$OS_ $KERNEL_RELEASE_\n"
	printf  "\n$ARCH_"
	[[ -n $CPU_TEMP_ ]] && printf "  $CPU_TEMP_\n\n" || printf "\n\n"
	printf  "Memory:\t$MEMORY_ MB\nSwap:\t$SWAP_ MB\n"
	gpu_info
	printf  "\n"
}

system_info
update_drivers
